language: rust

rust: stable

cache:
  directories:
    - $HOME/.cargo/registry

before_cache:
  - rm -rf $HOME/.cargo/registry/index

env:
  - CXXFLAGS='-fstack-clash-protection -D_GLIBCXX_ASSERTIONS -Wformat -Wformat-security -fstack-protector-strong --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2'

matrix:
  fast_finish: true
  include:
    - name: "Test Coverage"
      compiler: clang-11
      os: linux
      dist: bionic
      rust: nightly
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main"
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          update: true
          packages:
            - clang-11
            - libsqlite3-dev
            - libcurl4-openssl-dev
            - libxml2-dev
            - libstfl-dev
            - libjson-c-dev
            - libncursesw5-dev
            - asciidoctor
      env:
        - COMPILER=clang++-11
        - PROFILE=1
        - REPORT_COVERAGE=yes
      before_install:
        - cargo install grcov

          # Can't have these in the `env` section above, because these settings break `cargo install`
        - export CARGO_INCREMENTAL=0
        - export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
        - export RUSTDOCFLAGS="-Cpanic=abort"
    - name: "i18nspector"
      addons:
        apt:
          packages:
            - i18nspector
      env:
        - CHECKS=i18nspector

install:
  - export CXX=$COMPILER
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd ${TRAVIS_BUILD_DIR}
  # CI builds take a while to provision, install dependencies and compile our
  # stuff. To maximize the benefits, we ask Make to process as many rules as
  # possible before failing. This enables developers to fix more errors before
  # re-submitting the code to CI, which should increase throughput.
  - if [ -z "$CHECKS" ]; then   make -j2 --keep-going all test   ; fi
  - if [ -z "$CHECKS" ]; then   make ci-check   ; fi
  - if [ "$CHECKS" = "i18nspector" ]; then   make run-i18nspector | tee i18nspector.log && if `egrep '^(E|W):' i18nspector.log >/dev/null 2>&1` ; then false else true; fi   ; fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - if [ -n "${REPORT_COVERAGE}" ]; then   ./submit-to-coveralls.sh   ; fi
